### ISSUE TITLE
Integrate Auto Library

### ISSUE THREAD

**Issue by bhavinshah7** [graph-quilt/graphql-xtext#21]
Integrate [Auto Library](https://github.com/intuit/auto) with orchestrator to achieve the following:

* Calculate semantic version bumps from PRs
* Skip a release with the skip-release label
* Generate changelogs with headers, authors
* Use labels to create new changelog sections
* Generate a GitHub release

**Comment by pvs6275** [comment]
I can take this one

**Comment by skodamarthi** [comment]
@bhavinshah7 I can work on this if @pvs6275 is not planning to.
