### ISSUE TITLE
Upgrade xtext

### ISSUE THREAD

**Issue by ashpak-shaikh** [graph-quilt/graphql-xtext#22]
**Is your feature request related to a problem? Please describe.**

Update Xtext to [latest version](https://www.eclipse.org/Xtext/releasenotes.html)

**Describe the solution you'd like**

1. Create a [brand new project in xtext](https://www.eclipse.org/Xtext/documentation/index.html) with the same maven co-ordinates on eclipse, so we get all the build optimization too. 
2. Then copy paste [the grammar](https://github.com/graph-quilt/xtext-service-dsl/blob/master/com.intuit.dsl.service.parent/com.intuit.dsl.service/src/com/intuit/dsl/Service.xtext) from this project and make sure the build works fine.
3. Make sure the mirrors and snapshot are setup properly. 
4. Make sure the web-client-service-evaluator module is also present.

**Comment by skodamarthi** [comment]
@ashpak-shaikh Can I work on this?
